/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as URouteImport } from './routes/_u'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UIndexRouteImport } from './routes/_u/index'
import { Route as USubmissionsRouteImport } from './routes/_u/submissions'
import { Route as UProblemListRouteImport } from './routes/_u/problem-list'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AdminProblemIndexRouteImport } from './routes/admin/problem/index'
import { Route as AdminProblemNewRouteImport } from './routes/admin/problem/new'
import { Route as AdminProblemIdRouteImport } from './routes/admin/problem/$id'
import { Route as UProblemIdRouteImport } from './routes/_u/problem.$id'

const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const URoute = URouteImport.update({
  id: '/_u',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UIndexRoute = UIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => URoute,
} as any)
const USubmissionsRoute = USubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => URoute,
} as any)
const UProblemListRoute = UProblemListRouteImport.update({
  id: '/problem-list',
  path: '/problem-list',
  getParentRoute: () => URoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProblemIndexRoute = AdminProblemIndexRouteImport.update({
  id: '/problem/',
  path: '/problem/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProblemNewRoute = AdminProblemNewRouteImport.update({
  id: '/problem/new',
  path: '/problem/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProblemIdRoute = AdminProblemIdRouteImport.update({
  id: '/problem/$id',
  path: '/problem/$id',
  getParentRoute: () => AdminRoute,
} as any)
const UProblemIdRoute = UProblemIdRouteImport.update({
  id: '/problem/$id',
  path: '/problem/$id',
  getParentRoute: () => URoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/editor': typeof EditorRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/problem-list': typeof UProblemListRoute
  '/submissions': typeof USubmissionsRoute
  '/': typeof UIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/problem/$id': typeof UProblemIdRoute
  '/admin/problem/$id': typeof AdminProblemIdRoute
  '/admin/problem/new': typeof AdminProblemNewRoute
  '/admin/problem': typeof AdminProblemIndexRoute
}
export interface FileRoutesByTo {
  '/editor': typeof EditorRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/problem-list': typeof UProblemListRoute
  '/submissions': typeof USubmissionsRoute
  '/': typeof UIndexRoute
  '/admin': typeof AdminIndexRoute
  '/problem/$id': typeof UProblemIdRoute
  '/admin/problem/$id': typeof AdminProblemIdRoute
  '/admin/problem/new': typeof AdminProblemNewRoute
  '/admin/problem': typeof AdminProblemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_u': typeof URouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/editor': typeof EditorRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_u/problem-list': typeof UProblemListRoute
  '/_u/submissions': typeof USubmissionsRoute
  '/_u/': typeof UIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_u/problem/$id': typeof UProblemIdRoute
  '/admin/problem/$id': typeof AdminProblemIdRoute
  '/admin/problem/new': typeof AdminProblemNewRoute
  '/admin/problem/': typeof AdminProblemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/editor'
    | '/login'
    | '/signup'
    | '/problem-list'
    | '/submissions'
    | '/'
    | '/admin/'
    | '/problem/$id'
    | '/admin/problem/$id'
    | '/admin/problem/new'
    | '/admin/problem'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/editor'
    | '/login'
    | '/signup'
    | '/problem-list'
    | '/submissions'
    | '/'
    | '/admin'
    | '/problem/$id'
    | '/admin/problem/$id'
    | '/admin/problem/new'
    | '/admin/problem'
  id:
    | '__root__'
    | '/_u'
    | '/admin'
    | '/editor'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_u/problem-list'
    | '/_u/submissions'
    | '/_u/'
    | '/admin/'
    | '/_u/problem/$id'
    | '/admin/problem/$id'
    | '/admin/problem/new'
    | '/admin/problem/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  URoute: typeof URouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  EditorRoute: typeof EditorRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_u': {
      id: '/_u'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof URouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_u/': {
      id: '/_u/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UIndexRouteImport
      parentRoute: typeof URoute
    }
    '/_u/submissions': {
      id: '/_u/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof USubmissionsRouteImport
      parentRoute: typeof URoute
    }
    '/_u/problem-list': {
      id: '/_u/problem-list'
      path: '/problem-list'
      fullPath: '/problem-list'
      preLoaderRoute: typeof UProblemListRouteImport
      parentRoute: typeof URoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/problem/': {
      id: '/admin/problem/'
      path: '/problem'
      fullPath: '/admin/problem'
      preLoaderRoute: typeof AdminProblemIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/problem/new': {
      id: '/admin/problem/new'
      path: '/problem/new'
      fullPath: '/admin/problem/new'
      preLoaderRoute: typeof AdminProblemNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/problem/$id': {
      id: '/admin/problem/$id'
      path: '/problem/$id'
      fullPath: '/admin/problem/$id'
      preLoaderRoute: typeof AdminProblemIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_u/problem/$id': {
      id: '/_u/problem/$id'
      path: '/problem/$id'
      fullPath: '/problem/$id'
      preLoaderRoute: typeof UProblemIdRouteImport
      parentRoute: typeof URoute
    }
  }
}

interface URouteChildren {
  UProblemListRoute: typeof UProblemListRoute
  USubmissionsRoute: typeof USubmissionsRoute
  UIndexRoute: typeof UIndexRoute
  UProblemIdRoute: typeof UProblemIdRoute
}

const URouteChildren: URouteChildren = {
  UProblemListRoute: UProblemListRoute,
  USubmissionsRoute: USubmissionsRoute,
  UIndexRoute: UIndexRoute,
  UProblemIdRoute: UProblemIdRoute,
}

const URouteWithChildren = URoute._addFileChildren(URouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProblemIdRoute: typeof AdminProblemIdRoute
  AdminProblemNewRoute: typeof AdminProblemNewRoute
  AdminProblemIndexRoute: typeof AdminProblemIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminProblemIdRoute: AdminProblemIdRoute,
  AdminProblemNewRoute: AdminProblemNewRoute,
  AdminProblemIndexRoute: AdminProblemIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  URoute: URouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  EditorRoute: EditorRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
